apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artifact-registry-helm
  namespace: jenkins
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore

  target:
    name: artifact-registry-helm
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          jenkins.io/credentials-type: secretFile
        annotations:
          jenkins.io/credentials-description: "GCP service account (Artifact Registry / Helm )"
      data:
        filename: service-account.json
        data: |
          {{ .gcpSaJson }}

  data:
    - secretKey: gcpSaJson
      remoteRef:
        key: Jenkins
        property: jenkinsArtifactRegistry.json