apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artifact-registry
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore

  target:
    name: artifact-registry
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        annotations:
          jenkins.io/credentials-description: "GCP Artifact Registry service account for Building docker images"
      data:
        config.json: |
          {
            "auths": {
              "europe-southwest1-docker.pkg.dev": {
                "username": "_json_key",
                "password": {{ .gcpSaJson | quote }}
              }
            }
          }

  data:
    - secretKey: gcpSaJson
      remoteRef:
        key: Jenkins
        property: jenkinsArtifactRegistry.json