apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-github-ssh
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore
  target:
    name: jenkins-github-ssh
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          jenkins.io/credentials-description: "Jenkins private key to have access to github"
        labels:
          jenkins.io/credentials-type: basicSSHUserPrivateKey
      data:
        username: jenkins@techyon.dev
        privateKey: |
          {{ .privateKey }}
  data:
    - secretKey: privateKey
      remoteRef:
        key: Jenkins
        property: privateKeyForJenkins.txt