apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-gpg-signing-key
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore
  target:
    name: jenkins-gpg-signing-key
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          jenkins.io/credentials-description: "Signing GPG key used for signing packages from Goreleaser."
        labels:
          jenkins.io/credentials-type: secretFile
      data:
        filename: signingkey
        data: |
          {{ .data }}
  data:
    - secretKey: data
      remoteRef:
        key: Jenkins
        property: signingGpg.txt