apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-gpg-signing-key-passphrase
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore
  target:
    name: jenkins-gpg-signing-key-passphrase
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          jenkins.io/credentials-description: "A passphrase for signing gpg key."
        labels:
          jenkins.io/credentials-type: secretText
      data:
        text: |
          {{ .text }}
  data:
    - secretKey: text
      remoteRef:
        key: Jenkins
        property: signingGpgPassphrase.txt