apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-ksa
#TODO: Can be used to create workload identity, works only witj GKE!
#  annotations:
#    iam.gke.io/gcp-service-account: ${this.serviceAccount!!.email}
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-create-pods-rolebindings

subjects:
  - kind: ServiceAccount
    name: jenkins-ksa
    namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-create-pods-role
  apiGroup: rbac.authorization.k8s.io