apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-docker-auth
  namespace: jenkins
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore

  target:
    name: jenkins-docker-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "europe-southwest1-docker.pkg.dev": {
                "username": "_json_key",
                "password": {{ .gcpSaJson | quote }}
              }
            }
          }

  data:
    - secretKey: gcpSaJson
      remoteRef:
        key: Jenkins
        property: jenkinsArtifactRegistry.json