apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-create-pods
  namespace: jenkins
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "secrets", "services", "configmaps"]
    verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-create-pods
  namespace: jenkins
subjects:
  - kind: ServiceAccount
    name: jenkins
roleRef:
  kind: Role
  name: jenkins-create-pods
  apiGroup: rbac.authorization.k8s.io