apiVersion: v1
kind: Secret
metadata:
  name: jenkins-github-app
  namespace: jenkins
  labels:
    jenkins.io/credentials-type: gitHubApp
stringData:
  appID: "368614"
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    TODO: Move it elsewhere?
    -----END RSA PRIVATE KEY-----

---

apiVersion: v1
kind: Secret
metadata:
  name: jenkins-github-ssh
  namespace: jenkins
  labels:
    jenkins.io/credentials-type: basicSSHUserPrivateKey
stringData:
  username: jenkins
  privateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    TODO: Move it elsewhere?
    -----END OPENSSH PRIVATE KEY-----

---

apiVersion: v1
kind: Secret
metadata:
  name: jenkins-docker-auth
  namespace: jenkins
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-docker-config>