replicaCount: 2

antiaff:
  enabled: true
  avoidRelease: pihole
  strict: false

serviceDns:
  type: LoadBalancer
  loadBalancerIP: 192.168.32.53
  port: 53

  annotations:
    metallb.io/allow-shared-ip: pihole-svc

serviceWeb:

  type: LoadBalancer
  port: 80
  annotations:
    metallb.io/allow-shared-ip: pihole-svc

ingress:
  enabled: true
  ingressClassName: nginx

  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cloudflare-ca
    gethomepage.dev/description: PIHole Administration Panel
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Administration
    gethomepage.dev/icon: piholevault.png
    gethomepage.dev/name: PIHole DNS

  hosts:
    - pihole.lab.techyon.dev

  tls:
    - secretName: pihole-tls
      hosts:
        - pihole.lab.techyon.dev
dnsmasq:
  customDnsEntries:
    - address=/k8s-1.home/192.168.33.3
    - address=/k8s-2.home/192.168.33.2
    - address=/k8s-3.home/192.168.33.7
    - address=/mikrotik.home/192.168.33.19
    - address=/nas.home/192.168.33.14
    - address=/pc.home/192.168.33.8
    - address=/router.home/192.168.33.1

env:
  TZ: "Europe/Warsaw"
  DNSMASQ_LISTENING: "all"
  PIHOLE_DNS_: "1.1.1.1;8.8.8.8"

persistentVolumeClaim:
  enabled: true
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi