apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-ca
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adrian.jutrowski@techyon.dev
    privateKeySecretRef:
      name: cloudflare-dns
    solvers:
      - dns01:
          cloudflare:
            email: adrian.jutrowski@techyon.dev
            apiTokenSecretRef:
              name: cloudflare-access-token
              key: token