apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool-32
  namespace: metallb
spec:
  addresses:
    #Reserve some ip addresses in case I need first n to be allocated for something like KUBE API
    - 192.168.32.10-192.168.32.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv-lb-pool-32
  namespace: metallb
spec:
  ipAddressPools:
    - lb-pool-32