ingress:
  enabled: true
  ingressClassName: nginx

  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cloudflare-ca
    gethomepage.dev/description: Helm Chart Repository
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: CI/CD
    gethomepage.dev/icon: helm.png
    gethomepage.dev/name: Chartmuseum

  hosts:
  - name: charts.lab.techyon.dev
    path: /
    tls: true
    tlsSecret: charts-tls

env:
  storage: google
  open:
    STORAGE_GOOGLE_BUCKET: techyon-393614-charts
    STORAGE_GOOGLE_PREFIX: charts
    ENABLE_OCI_API: "true"
    DISABLE_API: "false"

gcp:
  secret:
    enabled: true
    name: artifact-registry-helm
    key: service-account.json