apiVersion: trident.qnap.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-qts # Required. Name your backend in Kubernetes.
spec:
  version: 1
  storageDriverName: qnap-nas #Required. Support 'qnap-nas'(latest) or 'qnap-iscsi'
  backendName: qts # Required. Name your backend in QNAP CSI.

  managementLIF: http://192.168.33.14:8080 #Not Sure but this might have made it work due to HTTP insecure protocol. For home lab its okay
  dataLIF: 192.168.33.14
#  networkInterfaces: ["Adapter1"] # Optional. Your adapter name or leave it empty.
  credentials:
    name: qnap # Required. Enter the secret name set in metadata.name.
  debugTraceFlags:
    method: true
  storage: # Required. Define one or more virtual pools.
    - serviceLevel: pool1 # Required. Name your virtual pool.

      labels: # Required. Define custom labels for your virtual pool.
        performance: performance1
#      features: # Optional. Define features for your virtual pool.
#        tiering: Enable
    - serviceLevel: pool2

      labels:
        performance: performance2
      features:
        tiering: Enable
        raidLevel: "1"