apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qnap
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore

  target:
    name: qnap
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .qnapUsername }}"
        password: "{{ .qnapPassword }}"
        storageAddress: 192.168.33.14

  data:
    - secretKey: qnapUsername
      remoteRef:
        key: QNAP
        property: username
    - secretKey: qnapPassword
      remoteRef:
        key: QNAP
        property: password