apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
  annotations:
    # Apply AFTER the Helm chart, so CRDs exist
    argocd.argoproj.io/sync-wave: "10"
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  description: "GatewayClass managed by Envoy Gateway"