
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
serviceType: LoadBalancer


service:
  loadBalancerIP: 192.168.32.3

servers:
  - zones:
      - zone: home.arpa
      - zone: home.lab
      - zone: home.dev
    port: 53
    plugins:
      - name: errors
      - name: health
      - name: ready

      - name: etcd
        parameters: home.arpa home.lab home.dev
        configBlock: |-
          stubzones
          path /skydns
          endpoint http://etcd.etcd.svc.cluster.local:2379

      - name: cache
        parameters: 30
      - name: reload

  - zones:
      - zone: .
    port: 53
    plugins:
      - name: forward
        parameters: . 1.1.1.1 8.8.8.8
      - name: cache