apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artifact-registry-helm
spec:
  secretStoreRef:
    name: one-password
    kind: ClusterSecretStore

  target:
    name: artifact-registry-helm
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        service-account.json: |
          {{ .gcpSaJson }}

  data:
    - secretKey: gcpSaJson
      remoteRef:
        key: Jenkins
        property: jenkinsArtifactRegistry.json