apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: one-password
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.secrets.svc.cluster.local:8080
      vaults:
        Infrastructure: 1  # look in this vault
        #Shared: 2   # next look in here. error if not found
      auth:
        secretRef:
          connectTokenSecretRef:
            name: one-password-access-token
            namespace: secrets
            key: token