apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-oidc-client
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: google-oidc-client
    creationPolicy: Owner
    template:
      mergePolicy: Merge
      data:
        client-id: "138732748534-v50ig1jfefsmfnf910a8ns4gpj2sj120.apps.googleusercontent.com"
  data:
    - secretKey: client-secret
      remoteRef:
        key: GOOGLE_OIDC_SECRET